### ISSUE TITLE
pip中ntwork找不到了

### ISSUE THREAD

**Issue by keysaim** [chazzjimel/WeChat-AIChatbot-WinOnly#3]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

pip install -r requirements.txt

### 问题描述 😯

直接pip3 install ntwork==0.1.3就报错了：
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement ntwork==0.1.3 (from versions: none)
ERROR: No matching distribution found for ntwork==0.1.3

看起来报备删掉了啊

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by keysaim** [comment]
找到了：https://pypi.tuna.tsinghua.edu.cn/packages/09/51/93b8a700d4d0980d03fe883b13a4cf7b2b836445fc929b92aa1785b950aa/

**Comment by colakang** [comment]
ERROR: ntwork-0.1.3-cp38-cp38-win32.whl is not a supported wheel on this platform

WIN11直接安装的时候，报错，有什么解决办法吗？

**Comment by colakang** [comment]
下载的版本需要跟python版本对应的。
应该使用https://pypi.tuna.tsinghua.edu.cn/simple/ntwork/去选择对应的版本
