### ISSUE TITLE
已安装ntwork，但运行仍报错显示ntwork不存在

### ISSUE THREAD

**Issue by gudong-mengxi** [chazzjimel/WeChat-AIChatbot-WinOnly#4]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

已安装ntwork，但运行仍报错显示ntwork不存在
![image](https://github.com/chazzjimel/WeChat-AIChatbot-WinOnly/assets/126675675/de338409-075c-411d-b99e-3867ecb3bee1)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by keysaim** [comment]
你ntwork在哪里下载的，pip貌似找不到了吧

**Comment by gudong-mengxi** [comment]
> 你ntwork在哪里下载的，pip貌似找不到了吧

我之前在pypi里也搜不到，后面换了国内源就有了，不过作者说虚拟环境下python3 -m pip install ntwork此命令可以正常生效

**Comment by keysaim** [comment]
> python3 -m pip install ntwork

试了下国内各种源，依然是找不到，晕倒。能麻烦把你本地的打个包发下吗？

**Comment by keysaim** [comment]
找到了：https://pypi.tuna.tsinghua.edu.cn/packages/09/51/93b8a700d4d0980d03fe883b13a4cf7b2b836445fc929b92aa1785b950aa/

**Comment by barryken** [comment]
已经下载的，可以将lib/site-packages/ntwork*,copy过来使用。

**Comment by 1120825781** [comment]
已经放弃了 pip根本没用

**Comment by 1120825781** [comment]
看了你们的评论也没说怎么解决的
